#客户类型表
CREATE TABLE `hotel_customertype`(
`pk` INT(11) NOT NULL AUTO_INCREMENT,
`id` INT(11) NOT NULL,
`c_type` VARCHAR(20) NOT NULL,
`discount` INT(11) NOT NULL,
`remark` VARCHAR(40) NULL,
  PRIMARY KEY (`pk`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `hotel_livein`(
`pk` INT(11) NOT NULL AUTO_INCREMENT,
`in_no` INT(11) NOT NULL,
`r_no` VARCHAR(20) NOT NULL,
`r_type_id` INT(11) NOT NULL,
`c_type_id` INT(11) NOT NULL,
`m_id` VARCHAR(20) NOT NULL,
`renshu` INT(11) NOT NULL,
`in_time` VARCHAR(20) NOT NULL,
`daynum` INT(11) NOT NULL,
`forefigt` FLOAT NOT NULL,
`chk_no` VARCHAR(20) NOT NULL,
`remark` VARCHAR(40) NULL,
  PRIMARY KEY (`pk`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `hotel_engage`(
`pk` INT(11) NOT NULL AUTO_INCREMENT,
`c_type_id` INT(11) NOT NULL,
`m_id` VARCHAR(20) NOT NULL,
`r_type_id` INT(11) NOT NULL,
`r_no` VARCHAR(20) NOT NULL,
`end_time` VARCHAR(20) NOT NULL,
`remark` VARCHAR(40) NULL,
  PRIMARY KEY (`pk`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `hotel_checkout`(
`pk` INT(11) NOT NULL AUTO_INCREMENT,
`chk_no` INT(11) NOT NULL,
`in_no` INT(11) NOT NULL,
`daynum` INT(11) NOT NULL,
`money` FLOAT NOT NULL,
`chk_time` VARCHAR(20) NOT NULL,
`remark` VARCHAR(40) NULL,
  PRIMARY KEY (`pk`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `hotel_pwd`(
`pk` INT(11) NOT NULL AUTO_INCREMENT,
`userid` VARCHAR(20) NOT NULL,
`pwd` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`pk`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `hotel_customer`(
`pk` INT(11) NOT NULL AUTO_INCREMENT,
`c_type_id` INT(11) NOT NULL,
`m_id` VARCHAR(20) NOT NULL,
`m_name` VARCHAR(20) NOT NULL,
`sex` VARCHAR(20) NOT NULL,
`zj_no` VARCHAR(20) NOT NULL,
`m_tel` VARCHAR(20) NOT NULL,
`remark` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`pk`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `hotel_roomtype`(
`pk` INT(11) NOT NULL AUTO_INCREMENT,
`id` INT(11) NOT NULL,
`roomtype` VARCHAR(20) NOT NULL,
`bed` INT(11) NOT NULL,
`price` FLOAT NOT NULL,
`foregift` FLOAT NOT NULL,
`cl_room` VARCHAR(20) NOT NULL DEFAULT 'N',
`cl_price` FLOAT NOT NULL,
`remark` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`pk`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `hotel_roominfo`(
`pk` INT(11) NOT NULL AUTO_INCREMENT,
`num` VARCHAR(20) NOT NULL,
`r_type_id` INT(11) NOT NULL,
`states` INT(11) NOT NULL DEFAULT 1,
`r_tel` VARCHAR(20) NOT NULL,
`remark` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`pk`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

